//sherman,
locations_admission = [
	{
		"id":"shermanfunctionhall",
		"name":"Sherman - Hassenfeld Function Hall",
		"nickname":"Sherman",
		"function":"Sherman contains student dining, including Brandeis' kosher dining hall, on the ground floor and conference areas on the upper level, along with The Stein.",
		"description":"The Rita Dee and Harold Hassenfeld University Conference Center contains a banquet/lecture hall and six rooms for meetings and conferences. Below, the ground-floor dining hall of the George and Beatrice Sherman Student Center serves over 1,000 students daily and includes the university's kosher food preparation and dining facilities. The upper level includes The Stein, the campus pub/restaurant and the Feldberg Lounge.",
		"category":["dining","student life"],
		"area":["lower campus"],
		"nearby":["facultycenter","scc","rosiesouth","shapirodorm","usen"],
		"coordinates": {"type":"Polygon","coordinates":[
			[[42.366599, -71.260741],
			[42.366687, -71.260541],
			[42.366545, -71.260425],
			[42.366525, -71.260473],
			[42.366325, -71.260309],
			[42.366253, -71.260473],
			[42.366260, -71.260901],
			[42.366355, -71.260985],
			[42.366438, -71.260810],
			[42.366627, -71.260942],
			[42.366688, -71.260810]]
		]},
		"entrances":["shermanfunctionhall_e01","shermanfunctionhall_e02"],
	},
	admissions = {
		"id":"admissions",
		"name":"Carl and Ruth Shapiro Admissions Center",
		"nickname":"Admissions",
		"coordinates": {"type":"Polygon","coordinates":[
			[[42.364604, -71.260664], 
			[42.364611, -71.260819],
			[42.364489, -71.260878], 
			[42.364150, -71.261231], 
			[42.364074, -71.261022],
			[42.364386, -71.260705]]
		]},
		"function":"Admissions hosts tours and provides information about Brandeis to any interested parties.",
		"description":"The Carl and Ruth Shapiro Admissions Center features 20,000 square feet of space to accommodate a 100-seat presentation room, a welcome center, and a financial services satellite office. The center serves as the starting point for campus visits, information sessions and student-led tours, and it’s open most weekdays and a few Saturdays during the year.",
		"category":["offices"],
		"entrances":["admissions_e01","admissions_e02"],
		"nearby":["spingold","slosberg","greatlawn","bernstein-marcus","ridgewoodA","ridgewoodB","ridgewoodC","village"],
		"area":["lower campus"]
	},
{
		"id":"scc",
		"name": "Carl and Ruth Shapiro Campus Center",
		"nickname": "SCC",
		"coordinates": {"type":"Polygon","coordinates": [
			[[42.365528, -71.260574],
			[42.365736, -71.260538],
			[42.365733, -71.260315],
			[42.365894, -71.260192],
			[42.366005, -71.260338],
			[42.366120, -71.260064],
			[42.365793, -71.259663],
			[42.365548, -71.259941]],
		]},
		"function": "The SCC is home to many of Brandeis' media clubs, the bookstore, Women's Resource Center, WBRS, the Dharmic Prayer Space, and the Student Union. Students can access the SCC 24/7 and many can be found studying here.",
		"description":"The Shapiro Campus Center opened in 2002 and is the hub of student life on campus. The SCC is open to students 24 hours a day, seven days a week. Many student organizations, including Student Union, Waltham Group, Student Events, WBRS (the campus radio station), the newspaper offices, BTV offices, and many others can be found within the campus center. It continues to be the most student-centered, “out of the classroom building on campus. Although it is also home to the offices of the Dean of Student Life, Student Activities, and Department of Student Rights and Community Standards, students primarily utilize this building for social and extra curricular activities. It also contains Einstein Bros. Cafe, the campus Brandeis Bookstore, student art exhibition space, rehearsal spaces, meeting rooms, a computer library and the 250 seat Carl J. Shapiro Theater. This theater is home to the Undergraduate Theatre Collective, our student run theatre organization. They produce, act in and build sets for over ten shows a year, ranging from straight plays to musical theater to sketch comedy!",
		"category":["student life"],
		"entrances":["scc_e01","scc_e02","scc_e03","scc_e04"],
		"area":["lower campus"],
		"nearby":["greatlawn","fellowsgarden","facultycenter","bernstein-marcus","gryzmish","irving"],
		"telic" : ["to eat bagel", "to drink coffee"],
		"constitutive" : ["bookstore", "computer cluster", "einstein bros coffee", "coffee shop",
						"newspaper offices", "Student Union", "tickets", "theater"],
		"color" : [ "green", "greenish", "copper"],
		"shape": [ "angular" ],
	},
	{
		"id":"fellowsgarden",
		"name": "Fellows Garden",
		"nickname": "Fellows Garden",
		"coordinates": {"type":"Polygon","coordinates": [
			[[42.366813,-71.259628],
			[42.366375,-71.260151],
			[42.365813,-71.259543],
			[42.366023,-71.259101]]
		]},
		"function": "Fellows Garden is a nice place to hangout with friends in nice weather",
		"description":"Fellows Garden was dedicated on the occasion of Brandeis University's twenty-fifth commencement.",
		"category":["landscape"],
		"entrances":['fellowsgarden_c01','fellowsgarden_c02','fellowsgarden_c03'],
		"area":["lower campus"],
		"nearby":["scc","facultycenter","volen","rosiesouth","rosieeast","rosienorth"]
	},
	{
		"id":"greatlawn",
		"name": "The Great Lawn",
		"nickname": "Great Lawn",
		"coordinates": {"type":"Polygon","coordinates": [
			[[42.365256, -71.260295],
			[42.364860, -71.260703],
			[42.365101, -71.261341],
			[42.365428, -71.260770]]
		]},
		"function": "The Great Lawn is a nice place to hangout with friends during great weather!",
		"description":"The Great Lawn is one of students’ favorite expanses of green on campus. Here you will typically see students doing their homework, playing frisbee, or just catching some afternoon sunshine between classes. It is also the setting for our activities fair, which takes place at the beginning of each semester, when over 260 clubs recruit first-years and continuing undergrads to their groups.",
		"category":["landscape", "lawn"],
		"entrances":['scc_c07','scc_c08','scc_c09','scc_c10'],
		"area":["lower campus"],
		"nearby":["scc","admissions","facultycenter"]
	},
]
